import Constants from "expo-constants";

const colors = Constants.expoConfig.extra.colors;
const font = Constants.expoConfig.extra.font;
export const GlobalStyles = {
  colors: {
    primary: colors.primary,
    primaryVariant: colors.primaryVariant,
    secondary: colors.secondary,
    tertiery: colors.tertiery,
    tertiery80: colors.tertiery80,
    tertiery70: colors.tertiery70,
    tertiery50: colors.tertiery50,
    tertiery40: colors.tertiery40,
    tertiery20: colors.tertiery20,
    tertiery10: colors.tertiery10,
    textWhite: colors.textWhite,
    textBlack: colors.textBlack,
    active: colors.active,
    disabled: colors.disabled,
    error80: colors.error80,
    error50: colors.error50,
    error500: colors.error500,
    red: colors.red,
    gray500: colors.gray500,
    gray400: colors.gray400,
    backgroundInput: colors.backgroundInput,
    blue: colors.blue,
    green: colors.green,
    greenlight: colors.greenlight,
    grey: colors.grey,
    greylight: colors.greylight,
    yellow: colors.yellow,
    yellowlight: colors.yellowlight,
    browhite: colors.browhite,
    purple: colors.purple,
    dNeedfollowup: colors.d_needfollowup,
    dIncoming: colors.d_incoming,
    dDisposition: colors.d_disposition,
    dTodo: colors.d_todo,
    dSecretary: colors.d_secretary,
    dDelegation: colors.d_delegation,
    normal: colors.normal,
    high: colors.high,
    low: colors.low,
    approve: colors.green,
    return: colors.yellow,
    returntocomposer: colors.orange,
    reject: colors.red,
    warning50: colors.warning50,
    success50: colors.success50,
    info50: colors.info50,
  },
  font: {
    xs: font.xs,
    sm: font.sm,
    md: font.md,
    lg: font.lg,
    xl: font.xl,
    xxl: font.xxl,
    xxxl: font.xxxl,
    xxxxl: font.xxxxl,
    hd5: font.hd5,
    hd4: font.hd4,
    hd3: font.hd3,
    hd2: font.hd2,
    hd1: font.hd1,
  },
};
